# terminal -> kitty
bind=CTRL+ALT,t,spawn,kitty
bind=SUPER,escape,spawn,kitty

# file manager -> thunar
bind=SUPER,e,spawn,thunar

# browser -> brave
bind=SUPER,b,spawn,brave

# IDE -> neovim
bind=SUPER,z,spawn_shell,kitty -e nvim 

# screenshot -> msnap
bind=SUPER+SHIFT,s,spawn_shell,g=$(slurp -d) && [ -n "$g" ] && grim -g "$g" - | tee "$HOME/Pictures/Screenshots/$(date +%Y%m%d%H%M%S).png" | wl-copy

# wswitch
bind=ALT,Tab,spawn,wswitch next

# launcher -> rofi
bind=SUPER,space,spawn,rofi -show drun

# noctalia panels
bind=SUPER,s,spawn,noctalia msg panel-toggle control-center
bind=SUPER,comma,spawn,noctalia msg settings-toggle
bind=CTRL+ALT,delete,spawn,noctalia msg panel-toggle session

# quit mango
bind=SUPER+SHIFT,m,quit

# kill client
bind=SUPER,q,killclient

# reload config
bind=SUPER+SHIFT,r,reload_config

# scroller
bind=ALT,e,set_proportion,1.0
bind=ALT,x,switch_proportion_preset,

# layouts
circle_layout=fair,vertical_scroller,center_tile,dwindle,grid
bind=SUPER,n,switch_layout
bind=SUPER,f,setlayout,fair
bind=SUPER,v,setlayout,vertical_scroller
bind=SUPER,c,setlayout,center_tile
bind=super,d,setlayout,dwindle
bind=SUPER,t,setlayout,tile
bind=SUPER,y,setlayout,scroller

# tag navigation
bind=SUPER,Left,viewtoleft,0
bind=SUPER,Right,viewtoright,0
bind=CTRL+SUPER,Left,tagtoleft,0
bind=CTRL+SUPER,Right,tagtoright,0
bind=SUPER,l,viewtoright,0
bind=SUPER,h,viewtoleft,0
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client

bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

# move tags
bind=ALT,1,tagsilent,1,0
bind=ALT,2,tagsilent,2,0
bind=ALT,3,tagsilent,3,0
bind=ALT,4,tagsilent,4,0
bind=ALT,5,tagsilent,5,0
bind=ALT,6,tagsilent,6,0
bind=ALT,7,tagsilent,7,0
bind=ALT,8,tagsilent,8,0
bind=ALT,9,tagsilent,9,0

# window focus
bind=ALT,Left,focusdir,left
bind=ALT,h,focusdir,left
bind=ALT,Right,focusdir,right
bind=ALT,l,focusdir,right
bind=ALT,Up,focusdir,up
bind=ALT,k,focusdir,up
bind=ALT,Down,focusdir,down
bind=ALT,j,focusdir,down
bind=SUPER,Up,focusdir,up
bind=SUPER,Down,focusdir,down

# swap window
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right
bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,j,exchange_client,down
bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,l,exchange_client,right

# window grouping
bind=SHIFT+ALT,h,groupfocus,prev
bind=SHIFT+ALT,l,groupfocus,next
bind=SHIFT+ALT,Left,groupjoin,left
bind=SHIFT+ALT,Right,groupjoin,right
bind=SHIFT+ALT,Down,groupjoin,down
bind=SHIFT+ALT,Up,groupjoin,up
bind=SHIFT+ALT,q,groupleave

# window status
bind=SUPER,g,toggleglobal,
bind=SUPER,w,togglejump
bind=ALT,f,togglefloating,
bind=ALT,a,togglemaximizescreen,
bind=SUPER,i,minimized,
bind=SUPER,o,toggleoverlay,
bind=SUPER+SHIFT,I,restore_minimized
bind=ALT,z,toggle_scratchpad

# gaps
# bind=ALT+SHIFT,X,incgaps,1
# bind=ALT+SHIFT,Z,incgaps,-1
# bind=ALT+SHIFT,R,togglegaps

# move
bind=CTRL+SHIFT,Up,movewin,up
bind=CTRL+SHIFT,Down,movewin,down
bind=CTRL+SHIFT,Left,movewin,left
bind=CTRL+SHIFT,Right,movewin,right
mousebind=SUPER,btn_left,moveresize,curmove

# resizing
bind=CTRL+ALT,Up,resizewin,+0,-50
bind=CTRL+ALT,Down,resizewin,+0,+50
bind=CTRL+ALT,Left,resizewin,-50,+0
bind=CTRL+ALT,Right,resizewin,+50,+0
mousebind=SUPER,btn_right,moveresize,curresize

# media
bind=NONE,XF86AudioNext,spawn,playerctl next
bind=NONE,XF86AudioPrev,spawn,playerctl previous
bind=NONE,XF86AudioPlay,spawn,playerctl play-pause

bind=NONE,XF86AudioRaiseVolume,spawn,noctalia msg volume-up 2
bind=NONE,XF86AudioLowerVolume,spawn,noctalia msg volume-down 2
bind=NONE,XF86AudioMute,spawn,noctalia msg volume-mute
bind=NONE,XF86MonBrightnessUp,spawn,noctalia msg brightness-up
bind=NONE,XF86MonBrightnessDown,spawn,noctalia msg brightness-down
