# scroller
scroller_structs=20
scroller_default_proportion=0.9
scroller_focus_center=0
scroller_prefer_center=0
scroller_prefer_overspread=1
edge_scroller_pointer_focus=1
scroller_ignore_proportion_gaps=0
scroller_proportion_preset=0.6,0.9,1.0

# master
new_is_master=0
default_mfact=0.55
default_nmaster=1
smartgaps=1
center_master_overspread=1

# dwindle
dwindle_split_ratio=0.5
dwindle_hsplit=2

# overview
hotarea_size=10
enable_hotarea=0
ov_tab_mode=0
overviewgappi=5
overviewgappo=30

# misc
no_border_when_single=0
axis_bind_apply_timeout=100
focus_on_activate=1
idleinhibit_ignore_visible=0
sloppyfocus=0
warpcursor=1
focus_cross_monitor=0
focus_cross_tag=0
enable_floating_snap=1
snap_distance=30
drag_tile_to_tile=1
drag_tile_small=1
allow_tearing=1
syncobj_enable=1

#keyboard
repeat_rate=10
repeat_delay=250
xkb_rules_layout=us

# mouse
mouse_accel_profile=1
mouse_accel_speed=0.9
axis_scroll_factor=1.2
disable_trackpad=1

# tag rules
tagrule=id:1,layout_name:tile
tagrule=id:2,layout_name:tile
tagrule=id:3,layout_name:vertical_scroller
tagrule=id:4,layout_name:vertical_scroller
tagrule=id:5,layout_name:scroller
tagrule=id:6,layout_name:scroller
tagrule=id:7,layout_name:center_tile
tagrule=id:8,layout_name:center_tile
tagrule=id:9,layout_name:dwindle


# layer rules

# msnap
layerrule=layer_name:msnap, noanim:1, noblur:1

# screenshot
layerrule=noanim:1,noblur:1,layer_name:selection

# rofi
layerrule=animation_type_open:zoom, animation_type_close:zoom, noanim:0, layer_name:rofi

# wswitch
layerrule=animation_type_open:none, animation_type_close:none, noanim:0, layer_name:wswitch

# display
monitorrule=make:Microstep,model:MAG 271QPX E2,width:2560,height:1440,refresh:240,x:0,y:0

# autostart
exec-once=~/.config/mango/autostart.sh
exec-once=wswitch --daemon

source=./binds.conf
source=./visuals.conf
