# themes
cursor_size=32
cursor_theme=catppuccin-mocha-dark-cursors

# windows
border_radius=12
no_radius_when_single=0
focused_opacity=1.0
unfocused_opacity=1.0
borderpx=3
gappih=5
gappiv=5 gappoh=2
gappov=2
scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9
rootcolor=0x201b14ff
bordercolor=0xb4befeff
focuscolor=0xcba6f7ff
maximizescreencolor=0x89aa61ff
urgentcolor=0xad401fff
scratchpadcolor=0x516c93ff
globalcolor=0xb153a7ff
overlaycolor=0x14a57cff

# overview jump mode
jump_label_decorate_fg_color=0xcdd6f4ff
jump_label_decorate_bg_color=0x11111bff
jump_label_decorate_border_color=0x5062d9ff

# window grouping
group_bar_height=50
group_bar_decorate_fg_color=0xe0cafaff
group_bar_decorate_bg_color=0x1e1e2eff
group_bar_decorate_focus_fg_color=0x11111bff
group_bar_decorate_focus_bg_color=0xcba6f7ff
group_bar_decorate_border_color=0x421dc4ff
group_bar_decorate_border_width=4
group_bar_decorate_corner_radius=5
group_bar_decorate_padding_x=10
group_bar_decorate_padding_y=10
group_bar_decorate_font_desc=monospace Bold 16

# blur
blur=1
blur_layer=0
blur_optimized=1
blur_params_num_passes=2
blur_params_radius=4
blur_params_noise=0.02
blur_params_brightness=0.9
blur_params_contrast=0.9
blur_params_saturation=1.2

# shadows
shadows=0
layer_shadows=0
shadow_only_floating=1
shadows_size=10
shadows_blur=15
shadows_position_x=0
shadows_position_y=0
shadowscolor=0x000000ff

# animations
animations=1
layer_animations=1
animation_type_open=zoom
animation_type_close=slide
layer_animation_type_open=slide
layer_animation_type_close=slide
animation_fade_in=1
animation_fade_out=1
tag_animation_direction=1
zoom_initial_ratio=0.4
zoom_end_ratio=0.7
fadein_begin_opacity=0.5
fadeout_begin_opacity=0.8
animation_duration_move=500
animation_duration_open=400
animation_duration_tag=350
animation_duration_close=800
animation_duration_focus=400
animation_curve_open=0.46,1.0,0.29,1.1
animation_curve_move=0.46,1.0,0.29,1
animation_curve_tag=0.46,1.0,0.29,1
animation_curve_close=0.08,0.92,0,1
animation_curve_focus=0.46,1.0,0.29,1
animation_curve_opafadeout=0.58,0.98,0.58,0.98
animation_curve_opafadein=0.46,1.0,0.29,1
